const categories = [
  { name: 'Mens Hats', value: 'mens-hats' },
  { name: 'mens-pants', value: 'mens-pants' },
  { name: 'mens-jewelry', value: 'mens-jewelry' },
  { name: 'mens-slip-ons-shoes', value: 'mens-slip-ons-shoes' },
  { name: 'mens-denim-jackets', value: 'mens-denim-jackets' },
  { name: 'mens-straight-leg-jeans', value: 'mens-straight-leg-jeans' },
  { name: 'mens-jeans', value: 'mens-jeans' },
  { name: 'mens-gloves', value: 'mens-gloves' },
  { name: 'mens-boots', value: 'mens-boots' },
  { name: 'mens-shorts', value: 'mens-shorts' },
  { name: 'mens-tees-and-tshirts', value: 'mens-tees-and-tshirts' },
  { name: 'mens-shortsleeve-shirts', value: 'mens-shortsleeve-shirts' },
  { name: 'mens-cardigan-sweaters', value: 'mens-cardigan-sweaters' },
  { name: 'mens-sweaters', value: 'mens-sweaters' },
  { name: 'mens-sweatshirts', value: 'mens-sweatshirts' },
  { name: 'mens-outerwear', value: 'mens-outerwear' },
  { name: 'mens-underwear-and-socks', value: 'mens-underwear-and-socks' },
  { name: 'mens-chinos-and-khakis', value: 'mens-chinos-and-khakis' },
  { name: 'mens-accessories', value: 'mens-accessories' },
  { name: 'mens-jackets', value: 'mens-jackets' },
  { name: 'mens-athletic-shorts', value: 'mens-athletic-shorts' },
  { name: 'mens-athletic-shorts', value: 'mens-athletic-shorts' },
  { name: 'mens-athletic-shorts', value: 'mens-athletic-shorts' },
  { name: 'mens-longsleeve-shirts', value: 'mens-longsleeve-shirts' },
  { name: 'mens-slim-jeans', value: 'mens-slim-jeans' },
  { name: 'mens-polo-shirts', value: 'mens-polo-shirts' },
  { name: 'mens-socks', value: 'mens-socks' },
  { name: 'mens-slim-jeans', value: 'mens-slim-jeans' },
  { name: 'mens-sunglasses', value: 'mens-sunglasses' },
  { name: 'mens-wool-coats', value: 'mens-wool-coats' },
];
export default categories;
