// this arr is for the category dropdown menu 
const categories = [
  { name: 'Mens Hats', value: 'mens-hats' },
  { name: 'Mens pants', value: 'mens-pants' },
  { name: 'Mens jewelry', value: 'mens-jewelry' },
  { name: 'Mens slip-ons-shoes', value: 'mens-slip-ons-shoes' },
  { name: 'Mens denim-jackets', value: 'mens-denim-jackets' },
  { name: 'Mens straight-leg-jeans', value: 'mens-straight-leg-jeans' },
  { name: 'Mens jeans', value: 'mens-jeans' },
  { name: 'Mens gloves', value: 'mens-gloves' },
  { name: 'Mens boots', value: 'mens-boots' },
  { name: 'Mens shorts', value: 'mens-shorts' },
  { name: 'Men tees-and-tshirts', value: 'mens-tees-and-tshirts' },
  { name: 'Men shortsleeve-shirts', value: 'mens-shortsleeve-shirts' },
  { name: 'Men cardigan-sweaters', value: 'mens-cardigan-sweaters' },
  { name: 'Mens sweaters', value: 'mens-sweaters' },
  { name: 'Mens sweatshirts', value: 'mens-sweatshirts' },
  { name: 'Mens outerwear', value: 'mens-outerwear' },
  { name: 'Mens underwear-and-socks', value: 'mens-underwear-and-socks' },
  { name: 'Mens chinos-and-khakis', value: 'mens-chinos-and-khakis' },
  { name: 'Mens accessories', value: 'mens-accessories' },
  { name: 'Mens jackets', value: 'mens-jackets' },
  { name: 'Mens athletic-shorts', value: 'mens-athletic-shorts' },
  { name: 'Mens longsleeve-shirts', value: 'mens-longsleeve-shirts' },
  { name: 'Mens slim-jeans', value: 'mens-slim-jeans' },
  { name: 'Mens polo-shirts', value: 'mens-polo-shirts' },
  { name: 'Mens socks', value: 'mens-socks' },
  { name: 'Mens sunglasses', value: 'mens-sunglasses' },
  { name: 'Mens wool-coats', value: 'mens-wool-coats' },
];
export default categories;
